name: Clippy

on:
  - push
  - pull_request

jobs:
  substore:
    name: clippy
    strategy:
      matrix:
        os: [ubuntu-latest, macos-lastest]
         
    runs-on: ${{ matrix.os }}

    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Install deps
        run: sudo apt-get -y update && sudo apt-get -y install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev pkg-config clang
      
      - name: Lint
        run: cargo clippy -- -D warnings
