
name: build

on:
   pull_request:
   push:
    branches:
      - main
      - feature/backups
jobs:
  provisioner:
    strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'pnpm'

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

      - name: Install deps for provisioner package
        working-directory: ./packages/provisioner
        run: pnpm install

      - name: Generate GQL schema
        working-directory: ./packages/provisioner
        run: pnpm codegen

      - name: Build provisioner
        working -directory: ./packages/provisioner
        run: pnpm build